import { 
  Heart, Zap, Laugh, Star, Rocket, Ghost 
} from 'lucide-react';
import { Genre, Movie } from './types';

export const movieDatabase: Record<string, Movie[]> = {
  "Feel Good": [
    { title: "Zindagi Na Milegi Dobara", year: "2011", desc: "Three friends on a bachelor trip to Spain find new meaning in life.", emoji: "🚗" },
    { title: "Happy Days", year: "2007", desc: "The ultimate engineering college nostalgia trip. A Sekhar Kammula classic.", emoji: "🎓" },
    { title: "3 Idiots", year: "2009", desc: "Two friends search for their lost companion while revisiting college memories.", emoji: "✏️" },
    { title: "Pelli Choopulu", year: "2016", desc: "A lazy engineer and an ambitious chef meet in a match-making chaos.", emoji: "🚚" },
    { title: "Bangalore Days", year: "2014", desc: "Three cousins move to Bangalore to fulfill their dreams. Pure warmth.", emoji: "🌆" },
    { title: "Godavari", year: "2006", desc: "A beautiful journey on a boat where two strangers find love and purpose.", emoji: "🚢" },
    { title: "Dear Zindagi", year: "2016", desc: "A girl learns to love her imperfections with help from an unconventional thinker.", emoji: "🌊" },
    { title: "Kumbalangi Nights", year: "2019", desc: "Four brothers in a fishing village find love and healing.", emoji: "🎣" },
    { title: "Bommarillu", year: "2006", desc: "A father's excessive concern clashes with his son's desire for freedom.", emoji: "🏠" },
    { title: "Munna Bhai M.B.B.S.", year: "2003", desc: "A goon goes to medical school. Magic hugs and life lessons!", emoji: "🏥" },
    { title: "Queen", year: "2013", desc: "A Delhi girl goes on her honeymoon alone after being dumped.", emoji: "🗼" },
    { title: "Wake Up Sid", year: "2009", desc: "A spoiled rich kid learns the value of independence and creativity.", emoji: "📸" },
    { title: "Dil Chahta Hai", year: "2001", desc: "Three inseparable friends navigate love and life in Mumbai and Goa.", emoji: "🏖️" },
    { title: "Jab We Met", year: "2007", desc: "A depressed businessman meets a bubbly girl on a train journey.", emoji: "🚆" },
    { title: "Yeh Jawaani Hai Deewani", year: "2013", desc: "Friends reunite for a wedding and confront their past and future.", emoji: "🏔️" },
    { title: "Rocket Singh", year: "2009", desc: "An average graduate starts his own business based on honesty.", emoji: "👔" },
    { title: "English Vinglish", year: "2012", desc: "A quiet housewife discovers her self-worth while learning English.", emoji: "🇺🇸" },
    { title: "Karwaan", year: "2018", desc: "Three lost souls find themselves on a road trip carrying a dead body.", emoji: "🚐" },
    { title: "Piku", year: "2015", desc: "A quirky father-daughter relationship on a road trip to Kolkata.", emoji: "💊" },
    { title: "Barfi!", year: "2012", desc: "A mute boy, an autistic girl, and a beautiful woman in a love triangle.", emoji: "🎈" },
    { title: "Dil Dhadakne Do", year: "2015", desc: "A dysfunctional wealthy family resolves their issues on a cruise.", emoji: "🚢" },
    { title: "Hindi Medium", year: "2017", desc: "Parents go to extreme lengths to get their daughter into a top school.", emoji: "🏫" },
    { title: "Chhichhore", year: "2019", desc: "College friends reunite to teach a lesson about failure and success.", emoji: "🏩" },
    { title: "Anand", year: "1971", desc: "A terminally ill man teaches his doctor how to live life to the fullest.", emoji: "🎈" },
    { title: "Anand (Telugu)", year: "2004", desc: "A heartwarming love story that starts with a morning coffee.", emoji: "☕" },
    { title: "Nuvvostanante Nenoddantana", year: "2005", desc: "A rich boy works as a farmer to prove his love to the girl's brother.", emoji: "🌾" },
    { title: "Manam", year: "2014", desc: "A magical story of reincarnation uniting three generations of a family.", emoji: "🕰️" },
    { title: "Seethamma Vakitlo Sirimalle Chettu", year: "2013", desc: "A simple family drama about the bond between two brothers.", emoji: "🌳" },
    { title: "Ustad Hotel", year: "2012", desc: "A young chef learns the secret of food and love from his grandfather.", emoji: "🍲" },
    { title: "Premam", year: "2015", desc: "Three stages of a man's romantic life. A modern cult classic.", emoji: "🦋" },
    { title: "Charlie", year: "2015", desc: "A girl traces the life of a free-spirited vagabond she's never met.", emoji: "🎨" },
    { title: "Home", year: "2021", desc: "A technologically challenged dad tries to connect with his sons.", emoji: "📱" },
    { title: "Sudani from Nigeria", year: "2018", desc: "A local football manager bonds with his injured Nigerian player.", emoji: "⚽" },
    { title: "Om Shanti Oshana", year: "2014", desc: "A spirited girl decides to pursue her crush, no matter how long it takes.", emoji: "🍇" },
    { title: "96", year: "2018", desc: "High school sweethearts meet at a reunion after 22 years.", emoji: "💛" },
    { title: "Mozhi", year: "2007", desc: "A musician falls in love with a deaf and mute girl. Pure music.", emoji: "🎻" },
    { title: "Kanda Naal Mudhal", year: "2005", desc: "Two people who hate each other eventually fall in love.", emoji: "🥊" },
    { title: "Vaaranam Aayiram", year: "2008", desc: "A son's tribute to his father through the various stages of his life.", emoji: "🎸" },
    { title: "Sarkari Hiriya Prathamika Shaale", year: "2018", desc: "Kids fight to save their Kannada medium school in a border town.", emoji: "🏫" },
    { title: "Lucia", year: "2013", desc: "An usher suffering from insomnia takes a pill that blurs reality.", emoji: "💊" },
    { title: "Kapoor & Sons", year: "2016", desc: "Two estranged brothers return home to their dysfunctional family.", emoji: "👨‍👩‍👦" },
    { title: "Jaane Tu... Ya Jaane Na", year: "2008", desc: "Two best friends refuse to believe they are in love with each other.", emoji: "🐱" },
    { title: "Band Baaja Baaraat", year: "2010", desc: "Two partners start a wedding planning business in Delhi.", emoji: "🎉" },
    { title: "Bareilly Ki Barfi", year: "2017", desc: "A love triangle involving a writer, a publisher, and a bully.", emoji: "📖" },
    { title: "Swades", year: "2004", desc: "A NASA scientist returns to India and finds his roots.", emoji: "💡" },
    { title: "Konchem Ishtam Konchem Kashtam", year: "2009", desc: "A son tries to reunite his divorced parents for his love.", emoji: "🧩" },
    { title: "Mithunam", year: "2012", desc: "An elderly couple lives a self-sufficient and romantic life.", emoji: "👵" }
  ],
  "Action": [
    { title: "RRR", year: "2022", desc: "Fire and Water unite to take down the British Empire. Mass euphoria.", emoji: "🔥" },
    { title: "K.G.F: Chapter 2", year: "2022", desc: "Rocky Bhai takes over the gold fields. High voltage action.", emoji: "🔨" },
    { title: "Vikram", year: "2022", desc: "A ghost agent hunts down a drug cartel. Rolex sir incoming!", emoji: "🦁" },
    { title: "Baahubali 2", year: "2017", desc: "The epic conclusion to the Mahishmati saga.", emoji: "🐘" },
    { title: "Sholay", year: "1975", desc: "The greatest Indian curry western ever made. Gabbar Singh!", emoji: "🐎" },
    { title: "Jawan", year: "2023", desc: "A father-son duo fights corruption. SRK in mass avatar.", emoji: "🤕" },
    { title: "Kaithi", year: "2019", desc: "A prisoner, a truck, and a night full of drug busts. No songs, just action.", emoji: "🚛" },
    { title: "Pokiri", year: "2006", desc: "The movie that defined Mahesh Babu's career. Twist at the end!", emoji: "🔫" },
    { title: "Salaar", year: "2023", desc: "Two friends become enemies in the dystopian city of Khansaar.", emoji: "🦖" },
    { title: "Gangs of Wasseypur", year: "2012", desc: "A multi-generational revenge saga in the coal mafia heartland.", emoji: "💣" },
    { title: "War", year: "2019", desc: "Mentor vs Protégé. Hrithik and Tiger in a style face-off.", emoji: "🚁" },
    { title: "Pathaan", year: "2023", desc: "An exiled spy returns to stop a biological attack on India.", emoji: "🕵️" },
    { title: "Tiger 3", year: "2023", desc: "Tiger and Zoya return to save their family and country.", emoji: "🧣" },
    { title: "Dhoom 2", year: "2006", desc: "Mr. A, a master thief, steals diamonds and hearts.", emoji: "💎" },
    { title: "Don", year: "2006", desc: "SRK steps into Amitabh's shoes. A stylistic chase begins.", emoji: "🕶️" },
    { title: "Agneepath", year: "2012", desc: "Vijay Deenanath Chauhan seeks revenge for his father's death.", emoji: "🔥" },
    { title: "Ghajini", year: "2008", desc: "A man with short-term memory loss hunts his lover's killer.", emoji: "🧠" },
    { title: "Singham", year: "2011", desc: "A strictly honest cop takes on a corrupt politician.", emoji: "🦁" },
    { title: "Simmba", year: "2018", desc: "A corrupt cop finds his conscience. Mind-blowing cameo.", emoji: "👮" },
    { title: "Uri: The Surgical Strike", year: "2019", desc: "Based on the true events of the 2016 surgical strikes.", emoji: "🎖️" },
    { title: "Shershaah", year: "2021", desc: "The story of PVC awardee Captain Vikram Batra. Yeh Dil Maange More!", emoji: "🏔️" },
    { title: "Lakshya", year: "2004", desc: "A lazy youth transforms into a disciplined army officer.", emoji: "🎯" },
    { title: "Border", year: "1997", desc: "The Battle of Longewala brought to life. Sandese Aate Hain.", emoji: "🏜️" },
    { title: "Gadar: Ek Prem Katha", year: "2001", desc: "A truck driver crosses the border for his love.", emoji: "🚙" },
    { title: "Business Man", year: "2012", desc: "Surya arrives in Mumbai to rule the mafia. Surya Bhai!", emoji: "🔫" },
    { title: "Magadheera", year: "2009", desc: "A warrior is reincarnated to win back his love.", emoji: "🏰" },
    { title: "Simhadri", year: "2003", desc: "NTR Jr in a furious avatar. A mass classic.", emoji: "🪓" },
    { title: "Chatrapathi", year: "2005", desc: "Refugees find a leader in Shivaji. Interval bang is legendary.", emoji: "🦈" },
    { title: "Okkadu", year: "2003", desc: "A Kabaddi player rescues a girl from a factionist in Kurnool.", emoji: "🏟️" },
    { title: "Athadu", year: "2005", desc: "A hitman hides in a village. Known for Trivikram's dialogues.", emoji: "🌾" },
    { title: "Khaleja", year: "2010", desc: "A cab driver is hailed as God by a remote village.", emoji: "🚕" },
    { title: "Race Gurram", year: "2014", desc: "Two brothers with opposite personalities take on a politician.", emoji: "🐎" },
    { title: "Sarileru Neekevvaru", year: "2020", desc: "An army major comes home to save a professor's family.", emoji: "🚆" },
    { title: "Ala Vaikunthapurramuloo", year: "2020", desc: "Swapped at birth, Bantu claims his place in style.", emoji: "🕺" },
    { title: "Akhanda", year: "2021", desc: "A fierce devotee of Shiva takes on evil. Roaring BGM.", emoji: "🔱" },
    { title: "Thuppakki", year: "2012", desc: "An army officer on vacation hunts down sleeper cells in Mumbai.", emoji: "💣" },
    { title: "Kaththi", year: "2014", desc: "A crook fights for the rights of farmers. Social message + Mass.", emoji: "💧" },
    { title: "Mankatha", year: "2011", desc: "A suspended cop plans a heist. Ajith's 50th film.", emoji: "💰" },
    { title: "Thani Oruvan", year: "2015", desc: "A cop chooses his enemy before the crime is committed.", emoji: "♟️" },
    { title: "Vada Chennai", year: "2018", desc: "A carrom player gets pulled into a gang war.", emoji: "🎱" },
    { title: "Asuran", year: "2019", desc: "A farmer protects his family from caste oppression.", emoji: "🔥" },
    { title: "Kantara", year: "2022", desc: "Man vs Nature vs Divine. The climax is pure adrenaline.", emoji: "🐗" },
    { title: "Animal", year: "2023", desc: "A son's obsessive love for his father turns him into a monster.", emoji: "🪓" },
    { title: "Leo", year: "2023", desc: "A peaceful cafe owner is hunted by his past.", emoji: "❄️" },
    { title: "Jailer", year: "2023", desc: "A retired jailer returns to save his son. Hukum!", emoji: "🕶️" }
  ],
  "Sci-Fi": [
    { title: "Kalki 2898 AD", year: "2024", desc: "Vishnu's final avatar descends. Epic scale dystopian mythos.", emoji: "⚡" },
    { title: "Eega", year: "2012", desc: "A housefly takes revenge. Rajamouli's most creative film.", emoji: "🪰" },
    { title: "Robo (Enthiran)", year: "2010", desc: "Chitti the Robot turns evil. A visual spectacle.", emoji: "🤖" },
    { title: "2.0", year: "2018", desc: "Chitti returns to fight a birdman entity made of cellphones.", emoji: "🦅" },
    { title: "Ra.One", year: "2011", desc: "A video game villain comes to life. Shah Rukh as a superhero.", emoji: "🎮" },
    { title: "Krrish", year: "2006", desc: "India's first major superhero. Mask, cape, and super jumps.", emoji: "🦸" },
    { title: "Krrish 3", year: "2013", desc: "Krrish fights a mutant army and a genius villain.", emoji: "🧬" },
    { title: "Koi... Mil Gaya", year: "2003", desc: "An intellectually disabled man befriends an alien. Jadoo!", emoji: "👽" },
    { title: "PK", year: "2014", desc: "An alien questions religious dogmas on Earth.", emoji: "📻" },
    { title: "Maanaadu", year: "2021", desc: "A political rally, a murder, and a time loop.", emoji: "♾️" },
    { title: "24", year: "2016", desc: "A watch mechanic fights his evil twin for a time-travel watch.", emoji: "⌚" },
    { title: "Aditya 369", year: "1991", desc: "The OG Indian time travel movie. Krishnadevaraya era visit!", emoji: "⏳" },
    { title: "Indru Netru Naalai", year: "2015", desc: "Two friends find a time machine and start a business.", emoji: "🕰️" },
    { title: "7aum Arivu", year: "2011", desc: "Bodhidharma's DNA is revived to fight a bio-war.", emoji: "🧬" },
    { title: "Dasavathaaram", year: "2008", desc: "Chaos theory connects 10 characters and a bio-weapon.", emoji: "☣️" },
    { title: "Tik Tik Tik", year: "2018", desc: "India's first space film. An asteroid threatens Chennai.", emoji: "🚀" },
    { title: "Antariksham 9000 KMPH", year: "2018", desc: "Astronauts try to fix a satellite to prevent a blackout.", emoji: "🛰️" },
    { title: "Oke Oka Jeevitham", year: "2022", desc: "Three friends travel back in time to fix their childhood regrets.", emoji: "🎸" },
    { title: "Project Z", year: "2024", desc: "A cop investigates a mystery involving cloning/future tech.", emoji: "🧪" },
    { title: "9 (Nine)", year: "2019", desc: "A scientist protects his son from a supernatural/cosmic entity.", emoji: "☄️" },
    { title: "Android Kunjappan", year: "2019", desc: "An old man bonds with a robot caregiver in a village.", emoji: "🤖" },
    { title: "Minnal Murali", year: "2021", desc: "A tailor gets lightning powers. A grounded superhero origin.", emoji: "⚡" },
    { title: "Brahmastra", year: "2022", desc: "Modern mythology with astras. Visuals are top notch.", emoji: "🔥" },
    { title: "Mr. India", year: "1987", desc: "A man finds a bracelet that makes him invisible. Mogambo khush hua!", emoji: "👓" },
    { title: "Action Replayy", year: "2010", desc: "A son goes back to the 70s to fix his parents' marriage.", emoji: "⏪" },
    { title: "Baar Baar Dekho", year: "2016", desc: "A man sees the future of his relationship in flashes.", emoji: "🔮" },
    { title: "Cargo", year: "2019", desc: "A spaceship processes souls for reincarnation. Very indie.", emoji: "🚢" },
    { title: "JL50", year: "2020", desc: "A plane that went missing 35 years ago crashes today.", emoji: "✈️" },
    { title: "Attack", year: "2022", desc: "A paralyzed soldier becomes a super-soldier with AI.", emoji: "🦾" },
    { title: "Ayalaan", year: "2024", desc: "An alien lands in Chennai and befriends a common man.", emoji: "👽" },
    { title: "I", year: "2015", desc: "A bodybuilder is deformed by a virus and seeks revenge.", emoji: "💉" },
    { title: "Churuli", year: "2021", desc: "Two cops enter a village stuck in a time/space loop.", emoji: "🌀" },
    { title: "Tumbbad", year: "2018", desc: "Greed for gold in a cursed womb. Atmospheric fantasy.", emoji: "💰" },
    { title: "Awe!", year: "2018", desc: "Multiple stories converge in a psychological sci-fi twist.", emoji: "🐟" },
    { title: "Taxiwala", year: "2018", desc: "A job seeker buys a possessed vintage car. Horror-SciFi.", emoji: "🚕" },
    { title: "Ismart Shankar", year: "2019", desc: "A cop's memory is transferred into a goon's brain.", emoji: "🧠" },
    { title: "Rocketry", year: "2022", desc: "Biopic of Nambi Narayanan, featuring liquid propulsion tech.", emoji: "🚀" },
    { title: "Mission Mangal", year: "2019", desc: "The story of India's first Mars orbiter mission.", emoji: "🪐" },
    { title: "Ghatotkachudu", year: "1995", desc: "A tech-savvy rakshasa helps a family. Nostalgia overload.", emoji: "🔮" },
    { title: "Carbon", year: "2018", desc: "A man searches for a lost treasure, blurring reality and dream.", emoji: "💎" },
    { title: "Time Story", year: "2016", desc: "Tamil time travel goodness (24).", emoji: "⌚" },
    { title: "Drona", year: "2008", desc: "A superhero fantasy film (watch for the attempt!).", emoji: "⚔️" },
    { title: "Love Story 2050", year: "2008", desc: "A time travel romance to a futuristic Mumbai.", emoji: "🐻" },
    { title: "Creature 3D", year: "2014", desc: "Bipasha vs a monster in the hills.", emoji: "👹" },
    { title: "Oh! Baby", year: "2019", desc: "A 70-year-old grandma magically becomes 24 again.", emoji: "👵" }
  ],
  "Comedy": [
    { title: "Hera Pheri", year: "2000", desc: "Babu Bhaiya, Raju, and Shyam get a wrong number.", emoji: "☎️" },
    { title: "Phir Hera Pheri", year: "2006", desc: "The trio gets scammed by a scheme to double money.", emoji: "💰" },
    { title: "Hungama", year: "2003", desc: "A case of mistaken identities in a Mumbai mansion.", emoji: "🤪" },
    { title: "Hulchul", year: "2004", desc: "Two warring families and a fake drama of love.", emoji: "🎭" },
    { title: "Malamaal Weekly", year: "2006", desc: "A villager wins the lottery but dies of shock.", emoji: "🎟️" },
    { title: "Bhool Bhulaiyaa", year: "2007", desc: "Avani or Manjulika? Psychological horror comedy.", emoji: "🏰" },
    { title: "Chup Chup Ke", year: "2006", desc: "A man pretends to be mute to avoid debt collectors.", emoji: "🤐" },
    { title: "Dhamaal", year: "2007", desc: "Four friends chase a hidden treasure in Goa. The big W!", emoji: "🌳" },
    { title: "Welcome", year: "2007", desc: "A don wants to marry off his sister to a decent guy.", emoji: "🥔" },
    { title: "Singh Is Kinng", year: "2008", desc: "Happy Singh becomes the king of the Australian underworld.", emoji: "👑" },
    { title: "Lage Raho Munna Bhai", year: "2006", desc: "Gandhigiri! Munna starts hallucinating Bapu.", emoji: "📻" },
    { title: "Vicky Donor", year: "2012", desc: "A fertility expert convinces a boy to become a sperm donor.", emoji: "🧪" },
    { title: "Bala", year: "2019", desc: "A young man struggles with premature balding.", emoji: "🧢" },
    { title: "Dream Girl", year: "2019", desc: "A man can talk in a woman's voice, chaos follows.", emoji: "📞" },
    { title: "Stree", year: "2018", desc: "O Stree Kal Aana! Horror comedy done right.", emoji: "👻" },
    { title: "Go Goa Gone", year: "2013", desc: "Zombies attack a rave party in Goa.", emoji: "🧟" },
    { title: "Delhi Belly", year: "2011", desc: "Three roommates get mixed up with diamond smugglers.", emoji: "💎" },
    { title: "Fukrey", year: "2013", desc: "Four backbenchers try to make easy money.", emoji: "💸" },
    { title: "Nuvvu Naaku Nachav", year: "2001", desc: "Venky's timing is unmatched. A Telugu comedy masterpiece.", emoji: "😂" },
    { title: "Manmadhudu", year: "2002", desc: "He hates women, she loves him. Paris episode is gold.", emoji: "🌹" },
    { title: "Malliswari", year: "2004", desc: "A princess in hiding and a bachelor banker.", emoji: "👸" },
    { title: "Sontham", year: "2002", desc: "Sunil's comedy track is legendary.", emoji: "🤣" },
    { title: "Venky", year: "2004", desc: "A group of friends on a train. The police station scene!", emoji: "🚂" },
    { title: "Dhee", year: "2007", desc: "Srinu Vaitla's peak comedy. Brahmanandam vs Srihari.", emoji: "🏠" },
    { title: "Ready", year: "2008", desc: "Kidnapping the wrong girl leads to a family reunion.", emoji: "🚙" },
    { title: "Dookudu", year: "2011", desc: "An undercover cop creates a fake reality show for his dad.", emoji: "🎥" },
    { title: "Jathi Ratnalu", year: "2021", desc: "Three innocent prisoners and a lot of nonsense logic.", emoji: "💎" },
    { title: "Ee Nagaraniki Emaindi", year: "2018", desc: "Short film makers try to make a movie in Goa.", emoji: "🎬" },
    { title: "Brochevarevarura", year: "2019", desc: "A kidnapping goes hilariously wrong.", emoji: "🎒" },
    { title: "Mathu Vadalara", year: "2019", desc: "Delivery boys get caught in a murder mystery. Meth!", emoji: "📦" },
    { title: "F2", year: "2019", desc: "Frustrated husbands try to escape their wives.", emoji: "💍" },
    { title: "Kick", year: "2009", desc: "A man does crazy things just for a 'kick'.", emoji: "🚲" },
    { title: "Panchathanthiram", year: "2002", desc: "Kamal Haasan and friends cover up a lie.", emoji: "✈️" },
    { title: "Michael Madana Kama Rajan", year: "1990", desc: "Quadruplets separated at birth. Confusion max.", emoji: "4️⃣" },
    { title: "Avvai Shanmugi", year: "1996", desc: "A father dresses as a nanny to see his daughter.", emoji: "👵" },
    { title: "Tenali", year: "2000", desc: "A psychiatrist treats a man with many phobias.", emoji: "mouse" },
    { title: "Soodhu Kavvum", year: "2013", desc: "A kidnapper with an imaginary girlfriend.", emoji: "🕶️" },
    { title: "Doctor", year: "2021", desc: "A stoic doctor takes down a human trafficking ring. Dark humor.", emoji: "💉" },
    { title: "Kolamavu Kokila", year: "2018", desc: "An innocent girl starts smuggling drugs for money.", emoji: "🎒" },
    { title: "Kalyanaraman", year: "2002", desc: "A ghost helps his brother find love.", emoji: "👻" },
    { title: "Kilukkam", year: "1991", desc: "Mohanlal and Jagathy in Ooty. Classic Malayalam comedy.", emoji: "🏔️" },
    { title: "Godha", year: "2017", desc: "Wrestling and comedy in a Kerala village.", emoji: "🤼" },
    { title: "Aadu", year: "2015", desc: "Shaji Pappan and his team fight for a goat.", emoji: "🐐" },
    { title: "Kunjiramayanam", year: "2015", desc: "Myths and legends of a quirky village called Desham.", emoji: "🌴" },
    { title: "Bhagam Bhag", year: "2006", desc: "A theatre group in London gets framed for murder.", emoji: "🎭" }
  ],
  "Thriller": [
    { title: "Drishyam", year: "2013", desc: "Georgekutty buries a secret (and a body) to save his family.", emoji: "⛏️" },
    { title: "Drishyam 2", year: "2021", desc: "The investigation reopens. Can he do it again?", emoji: "🚓" },
    { title: "Andhadhun", year: "2018", desc: "A blind pianist witnesses a murder. Or did he?", emoji: "🎹" },
    { title: "Kahaani", year: "2012", desc: "A pregnant woman searches for her husband in Kolkata.", emoji: "🤰" },
    { title: "Talaash", year: "2012", desc: "A cop investigates an accident while dealing with personal grief.", emoji: "🚘" },
    { title: "Raazi", year: "2018", desc: "A young girl is sent to Pakistan as a spy in 1971.", emoji: "📡" },
    { title: "Neerja", year: "2016", desc: "The true story of a flight attendant who saved lives during a hijack.", emoji: "✈️" },
    { title: "Pink", year: "2016", desc: "No means No. A lawyer fights for three women.", emoji: "⚖️" },
    { title: "Badla", year: "2019", desc: "A lawyer helps a woman accused of murder. Truth has layers.", emoji: "❄️" },
    { title: "A Wednesday", year: "2008", desc: "A common man calls the police and holds the city hostage.", emoji: "💣" },
    { title: "Special 26", year: "2013", desc: "Fake CBI officers raid politicians. Based on true events.", emoji: "💼" },
    { title: "Baby", year: "2015", desc: "A covert ops team tracks a terrorist across the globe.", emoji: "🌍" },
    { title: "Airlift", year: "2016", desc: "The evacuation of Indians from Kuwait during the war.", emoji: "✈️" },
    { title: "Article 15", year: "2019", desc: "A city cop investigates caste-based crimes in rural India.", emoji: "🔦" },
    { title: "Ugly", year: "2013", desc: "A girl goes missing, exposing the ugly side of humanity.", emoji: "🎭" },
    { title: "Raman Raghav 2.0", year: "2016", desc: "A serial killer finds his soulmate in a corrupt cop.", emoji: "🔧" },
    { title: "NH10", year: "2015", desc: "A couple's road trip turns into a nightmare.", emoji: "🛣️" },
    { title: "Ratsasan", year: "2018", desc: "A psycho killer targets schoolgirls. Intense cat and mouse.", emoji: "🤡" },
    { title: "Thani Oruvan", year: "2015", desc: "Good vs Evil. A scientist uses medical knowledge for crime.", emoji: "🔬" },
    { title: "Vikram Vedha", year: "2017", desc: "A cop and a gangster narrate stories to find the truth.", emoji: "😈" },
    { title: "Theuran Adhigaaram Ondru", year: "2017", desc: "Cops hunt down a ruthless dacoit gang across states.", emoji: "desert" },
    { title: "Dhuruvangal Pathinaaru", year: "2016", desc: "A retired cop narrates a case he couldn't solve.", emoji: "🦵" },
    { title: "Pizza", year: "2012", desc: "A delivery boy gets trapped in a haunted house.", emoji: "🍕" },
    { title: "Goodachari", year: "2018", desc: "Desi James Bond. A young agent is framed.", emoji: "🕵️" },
    { title: "Kshanam", year: "2016", desc: "An ex-boyfriend returns to find a missing child.", emoji: "girl" },
    { title: "HIT: The First Case", year: "2020", desc: "A cop with PTSD investigates a kidnapping.", emoji: "fire" },
    { title: "HIT: The Second Case", year: "2022", desc: "A laid-back cop hunts a serial killer in Vizag.", emoji: "🦷" },
    { title: "Evaru", year: "2019", desc: "A corrupt cop investigates a murder case with twists.", emoji: "🔫" },
    { title: "1: Nenokkadine", year: "2014", desc: "A rockstar with schizophrenia seeks his parents' killers.", emoji: "🎸" },
    { title: "Agent Sai Srinivasa Athreya", year: "2019", desc: "A funny detective finds a dead body on a railway track.", emoji: "🔎" },
    { title: "U-Turn", year: "2016", desc: "Traffic violators on a flyover die mysteriously.", emoji: "↩️" },
    { title: "Rangitaranga", year: "2015", desc: "A novelist discovers dark secrets in a village.", emoji: "🎭" },
    { title: "Kavaludaari", year: "2019", desc: "A traffic cop solves a decades-old murder mystery.", emoji: "💀" },
    { title: "Birbal", year: "2019", desc: "A lawyer reopens a closed murder case.", emoji: "⚖️" },
    { title: "Joseph", year: "2018", desc: "A retired cop investigates his ex-wife's death.", emoji: "🏥" },
    { title: "Memories", year: "2013", desc: "An alcoholic cop tracks a serial killer.", emoji: "🍷" },
    { title: "Mumbai Police", year: "2013", desc: "A cop loses his memory just after solving a high-profile case.", emoji: "🧠" },
    { title: "Ela Veezha Poonchira", year: "2022", desc: "Police wireless station on a hill. A murder happens.", emoji: "📻" },
    { title: "Iratta", year: "2023", desc: "Twin brothers, both cops, and a death inside a police station.", emoji: "👮‍♂️👮‍♂️" },
    { title: "Nayattu", year: "2021", desc: "Three cops on the run after being framed.", emoji: "🏃" },
    { title: "Jana Gana Mana", year: "2022", desc: "A courtroom drama that questions the system.", emoji: "⚖️" },
    { title: "Kurangu Bommai", year: "2017", desc: "A golden idol and a missing father.", emoji: "bag" },
    { title: "Por Thozhil", year: "2023", desc: "A rookie and a veteran cop hunt a serial killer.", emoji: "🔦" },
    { title: "Virupaksha", year: "2023", desc: "Black magic in a village. A skeptic solves the mystery.", emoji: "👁️" },
    { title: "Karthikeya 2", year: "2022", desc: "A quest to find Lord Krishna's anklet.", emoji: "⛰️" },
    { title: "13B", year: "2009", desc: "A TV serial predicts the future of a family.", emoji: "📺" },
    { title: "Manorama Six Feet Under", year: "2007", desc: "An amateur detective gets involved in a political conspiracy.", emoji: "🕵️" },
    { title: "Johnny Gaddaar", year: "2007", desc: "A heist goes wrong when one member betrays the others.", emoji: "💰" }
  ],
  "Drama": [
    { title: "Taare Zameen Par", year: "2007", desc: "Every child is special. A teacher changes a boy's life.", emoji: "🎨" },
    { title: "Dangal", year: "2016", desc: "A father trains his daughters to be world-class wrestlers.", emoji: "🤼" },
    { title: "Lagaan", year: "2001", desc: "Farmers play cricket against the British to avoid tax.", emoji: "🏏" },
    { title: "Chak De! India", year: "2007", desc: "A disgraced coach redeems himself with the women's hockey team.", emoji: "🏑" },
    { title: "Rang De Basanti", year: "2006", desc: "Students playing freedom fighters in a film turn into rebels.", emoji: "🕯️" },
    { title: "Udaan", year: "2010", desc: "A boy breaks free from his abusive father to pursue writing.", emoji: "🕊️" },
    { title: "The Lunchbox", year: "2013", desc: "A mistaken lunchbox delivery sparks a correspondence.", emoji: "🍱" },
    { title: "Masaan", year: "2015", desc: "Stories of loss and hope on the banks of the Ganges.", emoji: "🔥" },
    { title: "Haider", year: "2014", desc: "Hamlet adapted to Kashmir. Intense and tragic.", emoji: "❄️" },
    { title: "Rockstar", year: "2011", desc: "Pain makes art. Jordan's journey to musical fame.", emoji: "🎸" },
    { title: "Tamasha", year: "2015", desc: "Don't be a robot. Find your own story.", emoji: "🎭" },
    { title: "Highway", year: "2014", desc: "A girl finds freedom after being kidnapped.", emoji: "🛣️" },
    { title: "Bajrangi Bhaijaan", year: "2015", desc: "A man tries to take a mute Pakistani girl home.", emoji: "🐵" },
    { title: "Black", year: "2005", desc: "A blind and deaf girl and her teacher.", emoji: "🕶️" },
    { title: "Guzaarish", year: "2010", desc: "A paralyzed magician petitions for euthanasia.", emoji: "🎩" },
    { title: "My Name Is Khan", year: "2010", desc: "Rizwan Khan travels to meet the President. 'I am not a terrorist'.", emoji: "🇺🇸" },
    { title: "Mahanati", year: "2018", desc: "The tragic life of actress Savitri.", emoji: "📽️" },
    { title: "Jersey", year: "2019", desc: "A 36-year-old failed cricketer tries again for his son.", emoji: "🏏" },
    { title: "C/o Kancharapalem", year: "2018", desc: "Four unconventional love stories in a small town.", emoji: "❤️" },
    { title: "Vedam", year: "2010", desc: "Five stories converge at a hospital during a terrorist attack.", emoji: "🏥" },
    { title: "Gamyam", year: "2008", desc: "A journey of self-discovery on a motorbike.", emoji: "🏍️" },
    { title: "Prasthanam", year: "2010", desc: "Political power play within a family.", emoji: "🚩" },
    { title: "Arjun Reddy", year: "2017", desc: "A surgeon goes on a self-destructive path after a breakup.", emoji: "💉" },
    { title: "Sita Ramam", year: "2022", desc: "A letter from the past reveals a timeless love story.", emoji: "💌" },
    { title: "Soorarai Pottru", year: "2020", desc: "A common man dreams of starting a low-cost airline.", emoji: "✈️" },
    { title: "Jai Bhim", year: "2021", desc: "A lawyer fights for a tribal woman whose husband went missing.", emoji: "🐍" },
    { title: "Sarpatta Parambarai", year: "2021", desc: "Boxing clans in 1970s North Chennai clash.", emoji: "🥊" },
    { title: "Peranbu", year: "2018", desc: "A father tries to understand his daughter with cerebral palsy.", emoji: "🌊" },
    { title: "Pariyerum Perumal", year: "2018", desc: "A law student faces caste discrimination.", emoji: "🐕" },
    { title: "Maheshinte Prathikaaram", year: "2016", desc: "A photographer vows not to wear slippers until he takes revenge.", emoji: "📷" },
    { title: "The Great Indian Kitchen", year: "2021", desc: "The drudgery of a housewife's life. Hard hitting.", emoji: "🍽️" },
    { title: "Malik", year: "2021", desc: "The rise of a leader in a coastal community.", emoji: "⛴️" },
    { title: "Joji", year: "2021", desc: "Macbeth set in a rich plantation family.", emoji: "🎣" },
    { title: "777 Charlie", year: "2022", desc: "A loner finds purpose through a dog named Charlie.", emoji: "🐕" },
    { title: "Sapta Sagaradaache Ello", year: "2023", desc: "A love story separated by prison walls (Side A & B).", emoji: "🌊" },
    { title: "Thithi", year: "2015", desc: "Three generations react to a grandfather's death. Realistic.", emoji: "👴" },
    { title: "Sairat", year: "2016", desc: "Young love faces the wrath of caste politics.", emoji: "🚜" },
    { title: "Court", year: "2014", desc: "A folk singer is accused of abetting suicide.", emoji: "⚖️" },
    { title: "The Disciple", year: "2020", desc: "A vocalist struggles to achieve mastery in classical music.", emoji: "🎵" },
    { title: "Super 30", year: "2019", desc: "A mathematician teaches 30 poor students for IIT.", emoji: "📚" }
  ]
};

export const genres: Genre[] = [
  { name: "Feel Good", icon: Heart, color: "text-pink-400", gradient: "from-pink-500/20 to-pink-900/10", desc: "Heartwarming tales" },
  { name: "Sci-Fi", icon: Rocket, color: "text-purple-400", gradient: "from-purple-600/20 to-purple-900/10", desc: "Logic & Magic" },
  { name: "Action", icon: Zap, color: "text-orange-400", gradient: "from-orange-500/20 to-orange-900/10", desc: "High Voltage Mass" },
  { name: "Comedy", icon: Laugh, color: "text-yellow-400", gradient: "from-yellow-500/20 to-yellow-900/10", desc: "Laugh Out Loud" },
  { name: "Thriller", icon: Ghost, color: "text-cyan-400", gradient: "from-cyan-500/20 to-cyan-900/10", desc: "Edge of Seat" },
  { name: "Drama", icon: Star, color: "text-blue-400", gradient: "from-blue-500/20 to-blue-900/10", desc: "Pure Emotion" },
];
